Add video number
zooniverse/identified-chimps-site pull request #19
Opened 2016-12-18 16:41 UTC by jwidness

Add video number to the official video list.  This number is from the memory card and indicates the order of the videos on that card.

2016-12-18 16:44 UTC, jwidness commented
Since I can't run the code, I can't verify it's bug-free -- could you double check that it's not accidentally displaying the full filename or anything silly?
Thanks!

2016-12-20 15:44 UTC, astopy commented
@jwidness Just to let you know, I don't think I'll get to this this week so it won't be live until after Christmas/New Year.

2017-01-06 12:04 UTC, adammcmaster requested changes

2017-01-06 12:04 UTC, astopy commented on bin/generate-lists.rb
> +    video_num: document['metadata']['file'][-8..-5]
@jwidness Looks like this is missing a comma at the end of the line.

2017-01-06 14:41 UTC, jwidness commented
Oops!  Thanks for working on this -- no worries about the holidays, I was out too : )

2017-01-06 14:49 UTC, adammcmaster approved these changes

2017-01-06 14:49 UTC, merged

2017-01-06 14:49 UTC, astopy commented
Cool. We'll let this run over the weekend and double check the results next week.

2017-01-06 14:51 UTC, jwidness commented
Great, thanks!

2017-01-11 16:51 UTC, astopy commented
@jwidness Just to say, the video numbers are on there now.

2017-01-11 16:58 UTC, jwidness commented
Super!